name: sam_adapt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
#  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
#  - ca-certificates=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - cloudpickle=2.2.1
  - contourpy=1.0.5
  - cpuonly=2.0
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - cytoolz=0.12.0
  - dask-core=2023.4.1
  - dbus=1.13.18
  - expat=2.4.9
  - ffmpeg=4.3
  - fontconfig=2.14.1
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.4.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.26.0
  - importlib-metadata=6.0.0
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - jpeg=9e
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lame=3.100
  - lazy_loader=0.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=7.88.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm14=14.0.6
  - libnghttp2=1.46.0
  - libpng=1.6.39
  - libpq=12.9
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
#  - libxkbcommon=1.0.1
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
#  - monai=1.1.0
  - multidict=6.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.3
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.0.1
  - ply=3.11
  - protobuf=3.20.3
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
#  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.8.17
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pywavelets=1.4.1
  - pyyaml=6.0
#  - qt-main=5.15.2
#  - qt-webengine=5.15.9
#  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.2
  - requests=2.29.0
#  - scikit-image=0.20.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - setuptools=66.0.0
  - sip=6.6.2
  - snappy=1.1.9
  - sqlite=3.41.2
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - toolz=0.12.0
  - torchaudio=0.12.1
  - tornado=6.2
  - tqdm=4.65.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.8.1
  - zfp=0.5.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - aiosignal==1.2.0
    - alembic==1.10.4
    - appdirs==1.4.4
    - astor==0.8.1
    - asttokens==2.2.1
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - blinker==1.6.2
    - cachetools==4.2.2
    - certifi==2022.12.7
    - charset-normalizer==2.0.4
    - click==8.1.3
    - cmaes==0.9.1
    - colorama==0.4.6
    - colorlog==6.7.0
    - contextlib2==21.6.0
    - coverage==6.5.0
    - coveralls==3.3.1
    - cucim==23.4.1
    - cycler==0.11.0
    - databricks-cli==0.17.7
    - decorator==5.1.1
    - docker==6.1.1
    - docopt==0.6.2
    - einops==0.6.1
    - entrypoints==0.4
    - exceptiongroup==1.1.1
    - executing==1.2.0
    - filelock==3.12.0
    - fire==0.5.0
    - flask==2.3.2
    - fonttools==4.25.0
    - future==0.18.3
    - gdown==4.7.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.4
    - greenlet==2.0.2
    - gunicorn==20.1.0
    - h5py==3.8.0
    - huggingface-hub==0.14.1
    - iniconfig==2.0.0
    - ipython==8.13.1
    - itk==5.3.0
    - itk-core==5.3.0
    - itk-filtering==5.3.0
    - itk-io==5.3.0
    - itk-numerics==5.3.0
    - itk-registration==5.3.0
    - itk-segmentation==5.3.0
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - json-tricks==3.16.1
    - jsonschema==4.17.3
    - kornia==0.4.1
    - lmdb==1.4.1
    - lucent==0.1.0
    - mako==1.2.4
    - matplotlib-inline==0.1.6
    - mlflow==2.3.1
    - munkres==1.1.4
    - nibabel==5.1.0
    - ninja==1.11.1
    - nni==2.10
    - nptyping==2.5.0
    - opencv-python==4.7.0.72
    - openslide-python==1.1.2
    - optuna==3.1.1
    - parso==0.8.3
    - partd==1.2.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pluggy==1.0.0
    - pooch==1.4.0
    - prettytable==3.7.0
    - prompt-toolkit==3.0.38
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==11.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pydicom==2.3.1
    - pygments==2.15.1
    - pynrrd==1.0.0
    - pyqt5-sip==12.11.0
    - pyrsistent==0.19.3
    - pytest==7.3.1
    - pytest-mock==3.10.0
    - python-dateutil==2.8.2
    - pythonwebhdfs==0.2.3
    - pytorch-ignite==0.4.10
    - querystring-parser==1.2.4
    - regex==2023.5.5
    - requests-oauthlib==1.3.0
    - responses==0.23.1
    - rsa==4.7.2
    - schema==0.7.5
    - simplejson==3.19.1
    - six==1.16.0
    - smmap==5.0.0
    - soupsieve==2.4.1
    - sqlalchemy==2.0.12
    - sqlparse==0.4.4
    - stack-data==0.6.2
    - tabulate==0.9.0
    - tensorboardx==2.2
    - termcolor==2.3.0
    - threadpoolctl==2.2.0
    - tifffile==2021.7.2
    - tokenizers==0.12.1
    - toml==0.10.2
    - tomli==2.0.1
    - torch==1.12.1+cu113
    - torch-lucent==0.1.8
    - torchvision==0.13.1+cu113
    - traitlets==5.9.0
    - transformers==4.21.3
    - typeguard==3.0.2
    - types-pyyaml==6.0.12.9
    - wcwidth==0.2.6
    - websocket-client==1.5.1
    - websockets==11.0.3
    - werkzeug==2.3.4
