#!/bin/bash

#SBATCH -p gpu
#SBATCH --cpus-per-task 8
#SBATCH --gres gpu:A100:1
#SBATCH -n 3
#SBATCH --mem 40G
#SBATCH --job-name med_sam_cryopp 
#SBATCH -o ./output_ablation/10028_tail_1_adapter_test.log

## change weights, folder name in 2 places task and folder

python test.py -net 'sam' -mod 'sam_adpt' -exp_name '10028_tail_1_adapter_test' -sam_ckpt ./checkpoint/sam/sam_vit_h_4b8939.pth -weights ./logs_ablation/10028_tail_1_adapter_train/Model/checkpoint_best.pth -image_size 1024 -dataset CryoPPP -b 1 -data_path ./dataset/protein_data_2/10028 -prompt_approach 'points_grids'

